### ISSUE TITLE
Create actions.yml so it can be used locally with act

### ISSUE THREAD

**Issue by mariusgreve** [danger/kotlin#132]
To be able to run this action locally through [act](https://github.com/nektos/act) it requires an action.yml file to describe the action.
This file is fairly simple and should just need to reference the Dockerfile https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions

```
name: ...
description: ...
author: ...
runs:
  using: docker
  image: Dockerfile
```
