### ISSUE TITLE
Can we run the Danger-Kotlin in any non-Github CI?

### ISSUE THREAD

**Issue by anticafe** [danger/kotlin#203]
I want to run the Danger-Kotlin in CircleCI but doesn't find any official guide yet.
So for now, must we use Danger-Kotlin in Github Actions only?

**Comment by f-meloni** [comment]
Hey @anticafe, yes Danger-Kotlin works on CircleCI.
There are two main ways to use it with CircleCI:
- You can use a linux machine and install Danger Kotlin with the script
```sh
bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
source ~/.bash_profile
```

- You can use our pre built docker image for your job, which should be something like
```yml
  myjob:
    docker:
      - image: ghcr.io/danger/danger-kotlin:1.0.0
    steps:
      - checkout
      - run: danger-kotlin ci
```

The second option is probably easier if you just need to run a simple Dangerfile in parallel with your normal CI job
