### ISSUE TITLE
Brew installation failure danger-kotlin/0.2.0

### ISSUE THREAD

**Issue by Vacxe** [danger/kotlin#72]
Due installation via brew I got this isssue

```
==> make install PREFIX=/usr/local/Cellar/danger-kotlin/0.2.0
Last 15 lines from /Users/username/Library/Logs/Homebrew/danger-kotlin/01.make:

* Where:
Settings file '/private/tmp/danger-kotlin-20200226-23613-1a5qekz/kotlin-0.2.0/settings.gradle' line: 16

* What went wrong:
A problem occurred evaluating settings 'kotlin-0.2.0'.
> Could not get unknown property 'MPPTools' for settings 'kotlin-0.2.0' of type org.gradle.initialization.DefaultSettings.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 648ms
make: *** [build] Error 1
```

**Comment by Vacxe** [comment]
@aridai looks like a time for the new release? ;)

**Comment by f-meloni** [comment]
Yes, @gianluz is going to make a 0.3.0 :)

**Comment by gianluz** [comment]
https://github.com/danger/kotlin/pull/73

**Comment by f-meloni** [comment]
0.3.0 released, can you please give it a try? :)

**Comment by Vacxe** [comment]
@f-meloni 
Fix : #75 
Merge
Repeat

**Comment by f-meloni** [comment]
3.0.1 was released

**Comment by Vacxe** [comment]
@f-meloni hope u mean 0.3.1...

**Comment by f-meloni** [comment]
Yes, I do

**Comment by Vacxe** [comment]
```
==> make install PREFIX=/usr/local/Cellar/danger-kotlin/0.3.1
Last 15 lines from /Users/vacxe/Library/Logs/Homebrew/danger-kotlin/01.make:
Execution failed for task ':danger-kotlin:compileKotlinRunner'.
> Process 'command '/usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

```

**Comment by Vacxe** [comment]
See #77

**Comment by Vacxe** [comment]
@f-meloni which version of Java installed in your machine?

**Comment by f-meloni** [comment]
On my machine I have

```
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

Here on CI we just use the travis default `java` environment https://github.com/danger/kotlin/blob/master/.travis.yml

We also have a test project where I tested this latest version of brew, with those configurations

```yaml
language: oraclejdk11
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      install:
        - brew install danger/tap/danger-kotlin 
      script:
        - danger-kotlin ci
```

```yaml
language: openjdk13
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      install:
        - brew install danger/tap/danger-kotlin 
      script:
        - danger-kotlin ci
```
